import json
import requests
from pgm_llm_inference.core.config import InferenceConfig
from pydantic import BaseModel
import re
import time
from typing import Optional, Type, TypeVar
from pgm_llm_inference.utils import _extract_last_json_object

T = TypeVar("T", bound=BaseModel)

def local_llm_structured(prompt: str, schema: Type[T]) -> T:
    # print("Prompt: ", prompt)
    
    raw = local_llm(prompt)
    # print("Raw LLM: ", raw)
    try:
        data = _extract_last_json_object(raw)
    except Exception as e:
        raise RuntimeError(
            "Local LLM did not return valid JSON.\n"
            f"Raw output:\n{raw}"
        ) from e

    try:
        return schema.model_validate(data)
    except Exception as e:
        raise RuntimeError(
            f"JSON does not match schema {schema.__name__}.\n{data}"
        ) from e

def local_llm(prompt: str) -> str:
    """
    Query a local LLM server compatible with the OpenAI /chat/completions API.

    This function sends a prompt to a locally hosted LLM endpoint that supports
    streaming responses. It consumes Server-Sent Events (SSE) style outputs,
    aggregating the streamed text into a final string.

    Behavior:
        - Sends a POST request with streaming enabled
        - Parses OpenAI-like streamed delta chunks
        - Tolerates non-JSON fallback lines
        - Returns the concatenated text content

    Args:
        prompt: Input text prompt to be processed by the model.

    Returns:
        The full text output generated by the local LLM.

    Raises:
        RuntimeError: If the request fails or the server returns a non-200 status code.

    Example:
        >>> result = local_llm("Explain Bayes' Rule briefly.")
        >>> print(result)
    """
    config = InferenceConfig()
    local_url = config.local_url
    local_model = config.local_model 

    payload = {
        "model": local_model,
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.01,
        "stream": True,
    }
    try:
        resp = requests.post(local_url, json=payload, stream=True, timeout=60)
    except Exception as e:
        raise RuntimeError(f"Local LLM request failed: {e}")

    if resp.status_code != 200:
        # try to show body for debug
        body = ""
        try:
            body = resp.text
        except Exception:
            body = "<could not read body>"
        raise RuntimeError(f"Local LLM returned {resp.status_code}: {body}")

    # Attempt to consume streaming chunks. Many local servers send "data: ..." lines.
    text_parts = []
    for raw_line in resp.iter_lines(decode_unicode=True):
        if not raw_line:
            continue
        line = raw_line.strip()
        # Drop SSE prefix if present
        if line.startswith("data:"):
            line = line[len("data:"):].strip()
        if line in ("[DONE]", ""):
            continue
        # Try parse JSON chunk (OpenAI-like)
        try:
            obj = json.loads(line)
            # OpenAI-style streamed chunk structure: {"choices":[{"delta":{"content":"..."}}, ...]}
            choices = obj.get("choices")
            if choices:
                for c in choices:
                    delta = c.get("delta", {})
                    content = delta.get("content")
                    if content:
                        text_parts.append(content)
                    # some servers return full text in 'message' or 'text'
                    elif "message" in c and isinstance(c["message"], dict):
                        cont = c["message"].get("content")
                        if isinstance(cont, str):
                            text_parts.append(cont)
                    elif "text" in c and isinstance(c["text"], str):
                        text_parts.append(c["text"])
            else:
                # fallback: try top-level text
                if isinstance(obj.get("text"), str):
                    text_parts.append(obj["text"])
        except Exception:
            # Not JSON -- treat as plain text chunk
            text_parts.append(line)

    return "".join(text_parts)
